name: Build Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install app dependencies
        run: npm install

      - name: Seed app
        run: npm run seed:val-api

      - name: Build app
        run: npm run build

      - name: Capacitor Sync
        run: npx cap sync

      - name: Build debug apk
        run: cd android && gradle assembleDebug

      - name: Upload debug apk
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      # - name: Build app bundle
      #   run: cd android && gradle bundle

      # - name: Extract Android signing key from env
      #   run: |
      #     echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
      #     base64 -d android/release.jks.base64 > android/release.decrypted.jks

      # - name: Sign dev build
      #   run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      # - name: Upload release bundle
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: app-release
      #     path: android/app/build/outputs/bundle/release/app-release-signed.aab
      #     retention-days: 60
